//
// Created by wnoskowiak on 11.01.24.
//

#ifndef MIMUW_PW_2ND_LAB_ASSIGNMENT_WN_CASCADEWAKEUPHANDLER_H
#define MIMUW_PW_2ND_LAB_ASSIGNMENT_WN_CASCADEWAKEUPHANDLER_H

#endif //MIMUW_PW_2ND_LAB_ASSIGNMENT_WN_CASCADEWAKEUPHANDLER_H
