//
// Created by wnoskowiak on 12.01.24.
//

#ifndef MIMUW_PW_2ND_LAB_ASSIGNMENT_WN_ENVVARIABLEHANDLERS_H
#define MIMUW_PW_2ND_LAB_ASSIGNMENT_WN_ENVVARIABLEHANDLERS_H

int readWorldSize();

int readRank();

#endif //MIMUW_PW_2ND_LAB_ASSIGNMENT_WN_ENVVARIABLEHANDLERS_H
