//
// Created by wnoskowiak on 09.01.24.
//

#ifndef MIMUW_PW_2ND_LAB_ASSIGNMENT_WN_MESSAGEBUFFERHANDLER_H
#define MIMUW_PW_2ND_LAB_ASSIGNMENT_WN_MESSAGEBUFFERHANDLER_H

#endif //MIMUW_PW_2ND_LAB_ASSIGNMENT_WN_MESSAGEBUFFERHANDLER_H
